import type { Metadata } from "next";
import { Geist, Geist_Mono, Zen_Maru_Gothic, Yusei_Magic } from "next/font/google";
import "@/styles/global.scss";
import { Header } from "@/components/layouts/Header";
import { Footer } from "@/components/layouts/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
const zenMaruGothic = Zen_Maru_Gothic({
    variable: "--font-zen-maru-gothic",
    weight: ["400", "500"],
    display: "swap",
});

const yuseiMagic = Yusei_Magic({
    variable: "--font-yusei-magic",
    subsets: ["latin"],
    weight: ["400"],
});

export const metadata: Metadata = {
    title: "Mizuki Aoki",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <body className={`${zenMaruGothic.variable} ${yuseiMagic.variable}`}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
