name: Create Release PR

on:
    workflow_dispatch: {}

permissions:
    contents: write
    pull-requests: write

jobs:
    create-release-pr:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Create release PR
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  node .github/scripts/generateReleasePr.mjs
